### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by mr-bjerre** [jacksmith15/poetry-workspace-plugin#4]
I'm really excited to see this plugin evolve. IMO it's a missing piece in the python community - easily manage a monorepo.

Can you add some additional information how to install the plugin? You write that you need to clone this project but I assume you need to add the plugin in `pyproject.toml` as well. I've copied `poetry_workspace_plugin` folder to the root in my monorepo and  added the following to `pyproject.toml`.

```toml
[tool.poetry.plugins."poetry.application.plugin"]
poetry-workspace-plugin = "poetry_workspace_plugin:WorkspacePlugin"
```

Unfortunately I get `The command "workspace" is not defined.`. I'm using poetry version 1.1.12.
